server:
  port: 8180  # Port de la gateway

spring:
  application:
    name: api-gateway-basic

  cloud:
    gateway:
      routes:
        # Route pour product-service
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        # Route pour order-service
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**

        # Route pour stock-service
        - id: stock-service
          uri: http://localhost:8083
          predicates:
            - Path=/stock/**
