server:
  port: 8089

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route vers product-service
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        # Route vers order-service
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**

        # Route vers stock-service
        - id: stock-service
          uri: http://localhost:8083
          predicates:
            - Path=/stock/**
